### ISSUE TITLE
Collected feedback on items

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-TinkersSatchel#39]
I've been playing with this for a while in my modpack, and I really love the items. They're high quality, very polished, and mostly well balanced. However, I wanted to give my feedback on some of the items directly, with the context being that they are being used within a larger overhaul pack. This is obviously just my personal opinion and taste, so I could be pretty wrong on some of these!

### Mostly-Tame Mimic
The main issue I have with this item is that it's virtually impossible to tell when it's changed what item it's mimicking unless you're keeping your eyes on your item list like a hawk. Adding some sort of sound or other indicator would be nice. If there already is one, I haven't noticed.

### Sturdy Mug
One of my favorite items in the pack. I love the simplicity of it, love the model. Love that it's good on most characters but not in all situations.

### Percussive Maintenance
I really like this idea of this, but the simple fact is that it's mostly useless, even in mulitplayer. In singleplayer, it's almost exclusively a useless item, and it doesn't seem to work very reliably either (this may be an unrelated bug, though). You can of course heal your drones, but this is rarely useful, let alone even worth it. I think an interesting way to "fix" this problem would be to also heal the user whenever they successfully heal an ally. This would give it a use in singleplayer, and still give it an interesting niche in multiplayer.

### Macho Mustache
I love this item and its Void version, but I've gone back and forth on disabling it. Even though it's technically different than Focus Crystal, they still have a significant amount of design overlap. The differences aren't particularly noticeable in game. I would almost say that the Void version of the item could be turned into a Green instead, and the Macho Mustache removed. That might be a bit extreme, though.

### Armor Crystal
This is maybe a bit mean, but the model for this feels low quality. I actually think all it would take is a nicer texture or some nicer shine to make it look a lot better, though.

### Unstable Klein Bottle
I had to disable this one because it's just so annoying on melee characters. If you pick this one up, you have a chance to just screw with your attacks 8% of the time. Sadly, I don't know of a great way to fix this.

### Defibrillator
I like this item a lot, but I think the long description should be a little easier to understand. The short description makes perfect sense to me, but the long one should maybe say something like: "Your crit chance applies to all healing you do" instead of "outgoing". They mean about the same thing but should be easier to understand more often.

### Pinball Wizard
I put this in a separate issue, but this should probably be blacklisted from certain abilities.

### RC Controller
I feel like this item is insanely busted but I haven't tested it out too much. I actually don't think it even needs the attack speed buff (or at least, not quite so high), as the upside of being able to target them is already pretty good, and the downside is already pretty bad. I'm not sure, though.

### Silver Compass
Should be blacklisted from random effects. I also don't think that revealing the teleporter is enough of an upside for such a potentially severe drawback. I think it might be interesting if this item also instantly completed the teleporter for you if you kill the Boss. That being said, the upside of getting a bonus item is notable, so this might not be entirely necessary.

Most of the items I didn't mention I just love in general. I especially really love the artifacts. Safekeeping is an interesting idea, and Butterknife makes for some very chaotic runs. This mod is fantastic, super creative ideas.

**Comment by ThinkInvis** [comment]
- Mostly-Tame Mimic procs fairly often by default (batches every 3s). An indicator would get old fast, and part of the point of the item is its unpredictability.
- Percussive Maintenance is supposed to be an entirely selfless item used for saving allies/comboing with their on-healed items, so yes, it'll be less useful in singleplayer where your only allies can fly and avoid most damage. I could make it reflect some healing, but it'll be a much smaller amount due to this aspect of the design.
- I'm aware of the design overlap on Macho Moustache; I've been considering switching it to another stat or something.
- Yeah I know, Armor Crystal was one of the first items in this mod from back when I was even worse at modeling :( It's a reference to the Magic Armor from TLoZ, but I was too daunted by the prospect of modeling something like that so I made it a bootleg Rupee instead. May give it another pass at some point.
- Unstable Klein Bottle is intended to be a bad pick on melee characters, although it can still be used to give them some breathing room while surrounded + I did try to at least give them *something* recently (added damage to the proc, it didn't deal any before).
- The downside to RC Controller is bigger than you might think: a lot of the utility from turrets and drones comes from their ability to automatically focus on enemies that the player isn't. It also doesn't do much to aim assist; so the tradeoff is being able to chunk down single targets faster (not *a lot* faster, drones don't do much damage) vs. no longer having buddies to automatically take care of wisps for you.
- Silver Compass randomly triggering is a bug, and one I didn't know about! It should have `canBeRandomlyTriggered` set to false on its itemdef. I have a change to TILER2 coming up that may fix this (delaying itemdef registration until a later setup stage than creation), but I can't test it because I won't own the DLC for at least another 3 days.

**Comment by PollyEdaline** [comment]
- Mimic point is noted. Not sure if there's a better way to telegraph the effect then.
- Percussive might not actually be that bad at 2HP per shot, if the caveat is that you have to shoot allies. Leeching Seed in RiskyMod is already at 5%, which is obviously a big buff and much more useful, but doesn't feel gamebreaking.
- If we think about the design as being a sort of Hero/Villain thing (with the Void equivalent) , maybe the Macho Mustache could give you a slowly stacking damage/attack speed/whatever buff while in combat. 
- Armor Crystal is nice and noticeable at a distance, it just needs some polish!
- It's not bad design for certain items to be worse on certain characters, but most items aren't actively a hindrance on certain characters. Maybe it could knock enemies _up_ instead, which is generally easier to deal with. I'm not sure, though.
- I guess you're right about RC Controller. I really should do some more actual testing on it.

**Comment by PollyEdaline** [comment]
(the mustache suggestion overlaps with lidar, but they could just be collapsed into one item i guess)

**Comment by ThinkInvis** [comment]
Most of this has been addressed. Closing, but I'll open a new issue for the remaining points.
