### ISSUE TITLE
Bulwark and Item Drones are missing IDRs for Spare Drone Parts

### ISSUE THREAD

**Issue by gaforb** [ThinkInvis/RoR2-TinkersSatchel#52]
### Drones don't gain visible drone parts
Neither Item Drones nor Bulwark drones gain any weapons from this item, but they do still fire additional chain-gun shots

~~Command Terminal can call down config-disabled drones~~
~~Command Terminal cannot call down other mod-added drones~~

### Command Terminal can call down Equipment Drones with no Equipment
Would expect the same behaviour as item drones (a random equipment)

**Comment by gaforb** [comment]
Disregard the first two command terminal, didn't see the body list in it's config!

**Comment by ThinkInvis** [comment]
These are both most likely due to missing ItemDisplayRules, which are exceedingly difficult to set up -- and also don't actually break anything if missing, in most cases. As such, this is low-priority and unlikely to be fixed for a while.

Some equipments, especially modded ones, don't display a visible model on Equipment Drones. It's just impossible to tell because they don't indicate which equipment they have in any other way (e.g. in name like with Item Drones). IIRC, there's at least one vanilla drone that also doesn't have IDRs for Spare Drone Parts.

**Comment by ThinkInvis** [comment]
Turns out Equipment Drones were actually not receiving equipment, which I only found out when I added a tweak that adds equipment names to Equipment Drones' names. Fixed in 0cd8da176458ff4f6f4cb8e91793307b5cf8fcda. Missing IDRs for Spare Drone Parts is still a concern.
