### ISSUE TITLE
Item descriptions broken

### ISSUE THREAD

**Issue by Tincan2424** [ThinkInvis/RoR2-TinkersSatchel#76]
Whenever i hover my cursor over the items or when i pick them up it reads:"TINKERSATCHEL_(Item_name)_ITEM", and the descriptions dont load. i do play a fairly modded pack shy of 80~ish mods. from what ive heard ui mods can be causing it but the only UI mod im using currently is "BetterUI" and ive heard it shouldnt conflict, is this a error on my part or can it be the mods fault?

**Comment by Tincan2424** [comment]
If anyone would like to take a look at the mod-pack im using heres the r2mod manager code for the profile: 01895b28-cd4c-31f9-b9bb-04fda0d3e5f7

**Comment by Tincan2424** [comment]
### _**please**_

**Comment by ThinkInvis** [comment]
Closing due to staleness, and because I can't provide much support for very large modpacks. The most I can tell you is that display of raw language tokens, as described, is sometimes an indicator that something's stopping a mod from completing its loading process. I recommend performing a binary search for a conflicting mod: disable roughly half (then a quarter, then an eighth, etc.) of your active mods at a time to determine which half a conflicting mod might be in.
